
--COUNTRIES TABLE
CREATE TABLE COUNTRIES(
    COUNTRY_ID      CHAR(2) PRIMARY KEY,
    COUNTRY_NAME	VARCHAR(20) NOT NULL
);


--MEMBER_TYPE TABLE
CREATE TABLE MEMBER_TYPES(
TYPE_ID	            NUMBER(6,0)	PRIMARY KEY,
TYPE_DESCRIPTION	VARCHAR2(20) NOT NULL
);


--MEMBER_ROLE TABLE
CREATE TABLE MEMBER_ROLES(
ROLE_ID	            NUMBER(6,0)	PRIMARY KEY,
ROLE_DESCRIPTION	    VARCHAR2(20) NOT NULL
);


--DIVISIONS TABLE
CREATE TABLE DIVISIONS(
    DIVISION_ID	    NUMBER(6,0),
    DIVISION_NAME	VARCHAR2(20) NOT NULL,
    DIVISON_HEAD	NUMBER(6,0),
CONSTRAINT  DIV_ID_PK PRIMARY KEY(DIVISION_ID)
);

--CENTERS TABLE
CREATE TABLE CENTERS(
    CENTER_ID	    NUMBER(6,0),
    CENTER_TYPE 	VARCHAR2(20) NOT NULL,
    DIVISON_ID	    NUMBER(6,0),
CONSTRAINT  CENT_ID_PK PRIMARY KEY(CENTER_ID)
);


--LOCATIONS TABLE
CREATE TABLE LOCATIONS(
    LOCATION_ID	    NUMBER(6,0),
    STREET_ADDRESS  VARCHAR2(50) NOT NULL,
    CITY	        VARCHAR2(20) NOT NULL,
    STATE_PROVINCE  VARCHAR2(20) NOT NULL,
    POSTAL_CODE     VARCHAR2(10) NOT NULL,
    COUNTRY_ID      CHAR(2),
    CENTER_ID       NUMBER(6,0)  NOT NULL,
CONSTRAINT LOC_ID_PK PRIMARY KEY(LOCATION_ID),
CONSTRAINT LOC_COUNTRY_ID FOREIGN KEY(COUNTRY_ID) REFERENCES COUNTRIES,
CONSTRAINT LOC_CENTER_ID FOREIGN KEY(CENTER_ID) REFERENCES CENTERS
);

--STUDENTS TABLE
CREATE TABLE STUDENTS(
STUDENT_ID	        NUMBER(6,0),
PROGRAM_ID	        NUMBER(6,0),
ACDMC_LEVEL	        VARCHAR(16),
ENROLEMENT_STATUS	VARCHAR(16),
CONSTRAINT STU_ID_PK PRIMARY KEY(STUDENT_ID)
);

--MEMBERS TABLE
CREATE TABLE MEMBERS(
MEMBER_ID       NUMBER(6,0),
FIRST_NAME	    VARCHAR2(20) NOT NULL,
LAST_NAME	    VARCHAR2(20) NOT NULL,
MEMBER_TYPE	    NUMBER(6,0),
MEMBER_ROLE	    NUMBER(6,0),
MANAGER_ID	    NUMBER(6,0),
MEMBER_SINCE	DATE    NOT NULL,
LOCATION_ID	    NUMBER(6,0),
CONSTRAINT MEM_ID_PK PRIMARY KEY(MEMBER_ID)
--CONSTRAINT MEM_ID_FK FOREIGN KEY(MEMBER_ID) REFERENCES STUDENTS,
--CONSTRAINT MEM_MAN_ID_FK FOREIGN KEY(MANAGER_ID) REFERENCES MEMBERS
);

--PROGRAM SECTIONS TABLE
CREATE TABLE PROGRAM_SECTIONS(
SECTION_ID	        NUMBER(6,0),
DESCRIPTION	        VARCHAR(25)	NOT NULL,
COURSE_REFERENCE	VARCHAR(10)	NOT NULL,
INSTRUCTOR_ID	    NUMBER(6,0) NOT NULL,
LOCATION_ID	        NUMBER(6,0) NOT NULL,
CONSTRAINT PS_SEC_ID_PK PRIMARY KEY(SECTION_ID),
CONSTRAINT PS_SEC_ID_FK FOREIGN KEY (INSTRUCTOR_ID) REFERENCES MEMBERS,
CONSTRAINT PS_LOC_ID_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS
);


--PROGRAMS TABLE
CREATE TABLE PROGRAMS(
PROGRAM_ID	NUMBER(6,0),
DESCRIPTION	VARCHAR(25)	NOT NULL,
SECTION_ID	NUMBER(6,0),
DIVISION_ID	NUMBER(6,0),
CONSTRAINT PR_ID_PK PRIMARY KEY(PROGRAM_ID),
CONSTRAINT PR_SEC_FK FOREIGN KEY (SECTION_ID) REFERENCES PROGRAM_SECTIONS,
CONSTRAINT PR_DIV_FK FOREIGN KEY (DIVISION_ID) REFERENCES DIVISIONS
);


















DESCRIBE COUNTRIES;
DESCRIBE member_types;
DESCRIBE member_roles;
DESCRIBE divisions;
DESCRIBE centers;
DESCRIBE locations;
DESCRIBE students;
DESCRIBE members;
DESCRIBE program_sections;
DESCRIBE programs;























